// Canvassing custom-object column headers, extracted verbatim from the GHL export template.
export const TEMPLATE_HEADERS: string[] = [
  "MB Completed Application Now",
  "Yard Sign Requested",
  "Candidate Awareness",
  "EV Created New Plan",
  "Ok to Call",
  "Needs Transportation",
  "ED Asked About Support Status",
  "Opposition Reasons",
  "Conversation Quality",
  "Literature Drop",
  "MB Will Complete Today",
  "→ Opposition Other",
  "Canvasser Contact Name",
  "Ok to Text/SMS",
  "EV New Plan Date",
  "ED Confirmed Supporter",
  "Logistical Outcome Code",
  "Followup Required",
  "ED Confirmed Opposition",
  "MB Application Error Corrected",
  "Ok to Email",
  "Trigger Workflow 2 of Canvassing",
  "Followup Reason",
  "Contact Time",
  "EV New Plan Time",
  "Canvasser",
  "EV Voted Already Claimed",
  "ED Still Deciding",
  "Potential Donor",
  "Internal Notes",
  "MB Wants Paper Application",
  "Canvass Attempt Name",
  "ED Voted Today",
  "MB Changed To Early Vote",
  "Phone — Correct?",
  "EV Needs Transportation",
  "ED Voted For Candidate",
  "→ New Phone Number",
  "MB Changed To Election Day",
  "EV Changed To Election Day",
  "Vote Plan Barrier",
  "ED Did Not Confirm Vote",
  "Email — Correct?",
  "MB Has Received Ballot",
  "Persuaded To SL1",
  "EV Has Other Problem",
  "Primary Issue",
  "Contact Method",
  "ED Plan Confirmed",
  "→ New Email",
  "Primary Issue Other",
  "Disposition",
  "Event Invite",
  "MB Needs Replacement",
  "EV Problem Description",
  "Childcare Needed",
  "SL3 Persuaded To SL2",
  "MB Lost Ballot",
  "Canvassing For",
  "Current Support Level",
  "EV No Longer Voting",
  "ED New Plan Time",
  "Time Off Work Needed",
  "Volunteer Interest",
  "SL3 Now Opposition",
  "Turnout Barrier",
  "Needs Ride to Vote",
  "MB Check Status",
  "Issues (all that apply) Old",
  "Fulfillment Type",
  "Language Assistance",
  "→ Other Issue",
  "MB Pickup Scheduled",
  "ED Ride Scheduled",
  "Turnout Barrier Other",
  "Accessibility Needs",
  "Mail Ballot Stage",
  "Wants Reminder Calls",
  "MB Pickup Date",
  "Persuasion Outcome",
  "Undecided: Vote Plan (HP Script)",
  "Other Assistance",
  "ED Pickup Time",
  "Vote Plan",
  "MB Pickup Time",
  "Undecided: Vote Plan (LP Script)",
  "Support Strength (Post-Persuasion)",
  "→ Describe Other",
  "ED Will Vote No Time",
  "Vote Plan Notes",
  "Disposition (Phone)",
  "Issues (All That Apply)",
  "ED Unsure If Voting",
  "MB Will Mail Today Tomorrow",
  "Undecided: Vote Plan Notes",
  "Disposition (Door)",
  "MB Prefers Mail Declined Pickup",
  "ED Has Other Problem",
  "Persuasion Attempt Resulted in Opposition Status",
  "Selected General Issues",
  "Commitment Barrier",
  "ED Problem Description",
  "Disposition (Text)",
  "Primary Issues (All That Apply)",
  "MB Needs Help Completing",
  "MB Wants Vote In Person",
  "→ Primary Other Issue",
  "Shared Candidate Bio",
  "ED No Longer Voting",
  "Purpose of Contact",
  "ED Gave Polling Info (location/hours)",
  "Selected Primary Issues",
  "Canvassing Id",
  "MB No Longer Voting",
  "Discussed Their Priority Issues",
  "Invited to Meet-and-Greet",
  "Reports No Longer Voting in MB Application Stage",
  "Form Submission Longitude",
  "Offered Phone Follow-Up",
  "Reports No Longer Voting in MB Received Stage",
  "Form Submission Latitude",
  "Offered Additional Contact",
  "Reports No Longer Voting in MB Return Stage",
  "Form Submission Time",
  "Schedule Staff Follow-Up"
];
